INSERT INTO series (title, author_id, subgenre_id) VALUES ('Stormlight Archives', 1, 1);
INSERT INTO series (title, author_id, subgenre_id) VALUES ('The Kingkiller Chronicle', 2, 2);
INSERT INTO subgenres (name) VALUES ('Dragon lore');
INSERT INTO subgenres (name) VALUES ('Fantasy Fanfiction');
INSERT INTO books (title, year, series_id) VALUES ('Way of Kings', 2010, 1);
INSERT INTO books (title, year, series_id) VALUES ('Words of Radiance', 2014, 1);
INSERT INTO books (title, year, series_id) VALUES ('Oathbringer', 2017, 1);
INSERT INTO books (title, year, series_id) VALUES ('Name of the Wind', 2010, 2);
INSERT INTO books (title, year, series_id) VALUES ('Wise Mans Fear', 2014, 2);
INSERT INTO books (title, year, series_id) VALUES ('The Doors of Stxone', 2017, 2);
INSERT INTO characters (name, species, motto, author_id) VALUES ('Zoe', 'human', 'Get rich or die Tywin', 1);
INSERT INTO characters (name, species, motto, author_id) VALUES ('Beezle', 'bub', 'I aint yo mama', 2);
INSERT INTO characters (name, species, motto, author_id) VALUES ('Mmama', 'human', 'You aint my son', 2);
INSERT INTO characters (name, species, motto, author_id) VALUES ('Charlie', 'demon', 'It is what it is', 1);
INSERT INTO characters (name, species, motto, author_id) VALUES ('Clarke', 'mother', 'Eat your broccoli', 1);
INSERT INTO characters (name, species, motto, author_id) VALUES ('Harold', 'father', 'Well in the army...', 2);
INSERT INTO characters (name, species, motto, author_id) VALUES ('Rock', 'Herdazian', 'Airsick Lowlanders...', 1);
INSERT INTO characters (name, species, motto, author_id) VALUES ('Lopen', 'Herdazian', 'One armed blahblah', 2);
INSERT INTO authors (name) VALUES ('Brandon Sanderson');
INSERT INTO authors (name) VALUES ('Patrick Rothfuss');
INSERT INTO character_books (book_id, character_id) values (1, 1);
INSERT INTO character_books (book_id, character_id) values (2, 1);
INSERT INTO character_books (book_id, character_id) values (3, 1);
INSERT INTO character_books (book_id, character_id) values (1, 2);
INSERT INTO character_books (book_id, character_id) values (2, 2);
INSERT INTO character_books (book_id, character_id) values (3, 2);
INSERT INTO character_books (book_id, character_id) values (4, 3);
INSERT INTO character_books (book_id, character_id) values (5, 3);
INSERT INTO character_books (book_id, character_id) values (6, 3);
INSERT INTO character_books (book_id, character_id) values (4, 4);
INSERT INTO character_books (book_id, character_id) values (5, 4);
INSERT INTO character_books (book_id, character_id) values (6, 4);
INSERT INTO character_books (book_id, character_id) values (1, 7);
INSERT INTO character_books (book_id, character_id) values (2, 8);
INSERT INTO character_books (book_id, character_id) values (5, 5);
INSERT INTO character_books (book_id, character_id) values (6, 6);